mimic_models: {
  "APT_level1": "model_176500.onnx",
  
  "CR7_level1": "model_191500.onnx",

  "jump_forward_level1": "model_191500.onnx",
  "jump_forward_level2": "model_130500.onnx",
  "jump_forward_level3": "model_149000.onnx",

  "kick_level1": "model_168000.onnx",
  "kick_level2": "model_293000.onnx",
  "kick_level3": "model_240000.onnx",

  "Kobe_level1": "model_193000.onnx",

  "lebron_level1": "model_233500.onnx",
  "lebron_level2": "model_190000.onnx",

  "side_jump_level1": "model_135000.onnx",
  "side_jump_level2": "model_131500.onnx",
  "side_jump_level3": "model_245000.onnx",
}



start_upper_body_dof_pos: {
  "lift_up": 
  [
    0.0, 0.0, 0.0, # waist
    0.0, 0.0, 0.0, 0.0, # left shoulder and elbow
    0.0, 0.0, 0.0, # left wrist
    0.0, 0.0, 0.0, 0.0, # right shoulder and elbow
    0.0, 0.0, 0.0 # right wrist
  ],

  "APT_level1":
  [0.19964170455932617, 0.07710712403059006, -0.2882401943206787, 
  0.21672365069389343, 0.15629297494888306, -0.5167576670646667, 0.5782126784324646,
  0.0, 0.0, 0.0, 
  0.25740593671798706, -0.2504104673862457, 0.22500675916671753, 0.5127624273300171,
  0.0, 0.0, 0.0],

  

  "CR7_level1":
  [0.20492185652256012, -0.1423935443162918, -0.5196797847747803, 
  0.37753403186798096, 0.4606001079082489, -0.4165497124195099, 0.7984108328819275, 
  -0.09108904749155045, 0.0742582231760025, -0.10187414288520813, 
  0.24138350784778595, -0.35501086711883545, 0.29590970277786255, 0.9259377717971802, 
  0.0897110104560852, 0.05953628197312355, 0.07013951241970062],

  
  "jump_forward_level1":
  [0.045097291469573975, 0.11042889207601547, 0.3541450500488281, 
  -0.2664448320865631, 0.3803804814815521, -0.6423313021659851, 0.49415290355682373, 
  -0.10539000481367111, 0.007053654175251722, -0.14895562827587128, 
  -0.27388593554496765, -0.39011114835739136, 0.8009459376335144, 0.5996906757354736, 
  0.11178041994571686, 0.05555077642202377, 0.07856782525777817
  ],
  "jump_forward_level2":
  [-0.02629547007381916, 0.1044258326292038, -0.1473666876554489, 
  -0.1183449923992157, 0.36613816022872925, -0.6658874750137329, 0.40353667736053467, 
  -0.07663311809301376, 0.06474557518959045, -0.17684072256088257, 
  -0.11432900279760361, -0.3693147599697113, 0.7502599358558655, 0.5612908005714417, 
  0.09098311513662338, 0.07041975110769272, 0.06370417028665543
  ],
  "jump_forward_level3":
  [0.11907759308815002, -0.06782753765583038, -0.21148236095905304, 
  -0.058593880385160446, 0.43644383549690247, -0.6755354404449463, 0.44049447774887085, 
  -0.04251262918114662, 0.13801896572113037, -0.1174311712384224, 
  -0.01156798005104065, -0.3377457857131958, 0.781288743019104, 0.6981821060180664, 
  0.0764324739575386, 0.12200646847486496, 0.04586487635970116],


  "kick_level1":
  [0.19334529340267181, 0.26476186513900757, 0.5068590044975281, 
  -0.04159656539559364, 0.31694212555885315, -0.409045934677124, 0.9198440313339233, 
  -0.10894529521465302, 0.09830385446548462, -0.05800680071115494, 
  -0.11400521546602249, -0.49378490447998047, 0.7578608989715576, 0.8474284410476685, 
  0.11998694390058517, 0.08877772092819214, 0.042023640125989914],
  "kick_level2":
  [0.2032628059387207, 0.182508185505867, -0.22833460569381714, 
  0.13038116693496704, 0.4297596514225006, -0.529277503490448, 0.8634122610092163, 
  -0.11945795267820358, 0.11040791124105453, -0.07355817407369614, 
  0.07790787518024445, -0.3819763660430908, 0.8852471709251404, 0.7682194113731384, 
  0.12353815883398056, 0.08070569485425949, 0.03553816303610802],
  "kick_level3":
  [0.30520668625831604, 0.060712847858667374, -0.2506754398345947, 
  0.09942447394132614, 0.3964673578739166, -0.5988779067993164, 0.9304576516151428, 
  -0.13132517039775848, 0.11256328225135803, -0.08899586647748947, 
  0.08612339198589325, -0.34242063760757446, 0.9363580942153931, 0.8870665431022644, 
  0.14658823609352112, 0.10302004218101501, 0.07819974422454834],

  "Kobe_level1": [0.15386541187763214, 0.0628226026892662, -0.11425045132637024, 
  0.07208488881587982, 0.12677930295467377, -0.44947248697280884, 0.6861862540245056,
  0.0, 0.0, 0.0,
  0.06033417582511902, -0.32518187165260315, 0.18433918058872223, 0.6882569193840027,
  0.0, 0.0, 0.0],


  

  "lebron_level1":
  [0.28927478194236755, -0.0427047424018383, 0.3137834072113037, 
  -0.032295625656843185, 0.44610559940338135, -0.35555368661880493, 1.0250558853149414, 
  -0.14073072373867035, 0.12496963888406754, -0.11963929235935211, 
  -0.03556990623474121, -0.3175228536128998, 0.4563574194908142, 1.0163283348083496, 
  0.132579043507576, 0.130295991897583, 0.1369185745716095],
  "lebron_level2":
  [0.26498958468437195, 0.004183614160865545, 0.3286237120628357, 
  -0.1047021895647049, 0.4793112874031067, -0.3610142767429352, 0.8710411787033081, 
  -0.10773038119077682, 0.13804234564304352, -0.09281636774539948, 
  -0.11720383167266846, -0.34526848793029785, 0.7066057920455933, 0.7991378903388977, 
  0.10698656737804413, 0.12937703728675842, 0.11009333282709122],




  "side_jump_level1":
  [0.15126359462738037, 0.0714510902762413, -0.5199999809265137, 
  0.3450615108013153, 0.34631121158599854, -0.4137703478336334, 0.639528751373291, 
  -0.0391659215092659, 0.12899728119373322, -0.04680430516600609, 
  0.23275026679039001, -0.34249043464660645, 0.4032745659351349, 0.7589754462242126, 
  0.04312089830636978, 0.07626685500144958, 0.01097512524574995],

  "side_jump_level2":
  [ 0.20148296654224396, 0.07717499136924744, -0.21546435356140137, 
  0.1704193353652954, 0.33506959676742554, -0.3543175458908081, 0.3222774267196655, 
  -0.019805945456027985, 0.13857758045196533, -0.1175633892416954, 
  0.07796253263950348, -0.3726571798324585, 0.3958783745765686, 0.4751143455505371, 
  0.020584601908922195, 0.10585267841815948, 0.03447344899177551
  ],
  "side_jump_level3":
  [0.2192986011505127, 8.261951734311879e-05, -0.21791237592697144, 
  0.022316448390483856, 0.2905949652194977, -0.36345407366752625, 0.233949676156044, 
  -0.011479750275611877, 0.11892618983983994, -0.1468876451253891, 
  -0.11076739430427551, -0.33399146795272827, 0.3532547652721405, 0.3134865164756775, 
  0.007447139825671911, 0.10121755301952362, 0.05996187403798103
  ],




}

motion_length_s: {
  "lift_up": 11.067,

  "APT_level1": 7.66,


  "CR7_level1": 3.967,

  "jump_forward_level1": 3.76,
  "jump_forward_level2": 3.56,
  "jump_forward_level3": 4.26,


  "kick_level1": 3.96,
  "kick_level2": 3.36,
  "kick_level3": 4.56,


  "lebron_level1": 5.067,
  "lebron_level2": 6.967,

  "Kobe_level1": 4.16,


  "side_jump_level1": 3.06,
  "side_jump_level2": 3.56,
  "side_jump_level3": 3.66,


}